TrainerNames:
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "CAMPER@"
	db "PICNICKER@"
	db "POKé MANIAC@"
	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "COUPLE@"
	db "FISHERMAN@"
	db "SWIMMER@"
	db "ROUGHNECK@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "GUITARIST@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BLACK BELT@"
	db "RIVAL@"
	db "SWIMMER@"
	db "ROCKET@"
	db "SCIENTIST@"
	db "BOSS@"
	db "ROCKET@"
	db "ACE TRAINER@"
	db "ACE TRAINER@"
	db "ELITE FOUR@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "GENTLEMAN@"
	db "RIVAL@"
	db "CHAMPION@"
	db "ELITE FOUR@"
	db "CHANNELER@"
	db "ELITE FOUR@"
	db "ELITE FOUR@"
	db "HEX MANIAC@"
	db "TRAINER@"
