WonderTradeOTNames1:
	db "RED@@@@@" ; $00
	db "BLUE@@@@" ; $01
	db "GREEN@@@" ; $02
	db "YELLOW@@" ; $03
	db "ORANGE@@" ; $04
	db "GOLD@@@@" ; $05
	db "SILVER@@" ; $06
	db "CRYSTAL@" ; $07
	db "RUBY@@@@" ; $08
	db "SAFIRE@@" ; $09
	db "EMERALD@" ; $0a
	db "JADE@@@@" ; $0b
	db "DIAMOND@" ; $0c
	db "PEARL@@@" ; $0d
	db "PLATINA@" ; $0e
	db "HEART@@@" ; $0f
	db "SOUL@@@@" ; $10
	db "MIND@@@@" ; $11
	db "BLACK@@@" ; $12
	db "WHITE@@@" ; $13
	db "GRAY@@@@" ; $14
	db "X@@@@@@@" ; $15
	db "Y@@@@@@@" ; $16
	db "Z@@@@@@@" ; $17
	db "ALPHA@@@" ; $18
	db "OMEGA@@@" ; $19
	db "DELTA@@@" ; $1a
	db "LAMBDA@@" ; $1b
	db "THETA@@@" ; $1c
	db "ZETA@@@@" ; $1d
	db "SUN@@@@@" ; $1e
	db "MOON@@@@" ; $1f
	db "STAR@@@@" ; $20
	db "ASH@@@@@" ; $21
	db "GARY@@@@" ; $22
	db "LEAF@@@@" ; $23
	db "ETHAN@@@" ; $24
	db "LYRA@@@@" ; $25
	db "HIRO@@@@" ; $26
	db "KRIS@@@@" ; $27
	db "BRENDAN@" ; $28
	db "MAY@@@@@" ; $29
	db "WALLY@@@" ; $2a
	db "LUCAS@@@" ; $2b
	db "DAWN@@@@" ; $2c
	db "BARRY@@@" ; $2d
	db "HILBERT@" ; $2e
	db "HILDA@@@" ; $2f
	db "CHEREN@@" ; $30
	db "BIANCA@@" ; $31
	db "NATE@@@@" ; $32
	db "ROSA@@@@" ; $33
	db "HUGH@@@@" ; $34
	db "CALEM@@@" ; $35
	db "SERENA@@" ; $36
	db "SHAUNA@@" ; $37
	db "TREVOR@@" ; $38
	db "TIERNO@@" ; $39
	db "HAU@@@@@" ; $3a
	db "LILLIE@@" ; $3b
	db "GLADION@" ; $3c
	db "WES@@@@@" ; $3d
	db "MICHAEL@" ; $3e
	db "TODD@@@@" ; $3f
	db "OAK@@@@@" ; $40
	db "ELM@@@@@" ; $41
	db "IVY@@@@@" ; $42
	db "BIRCH@@@" ; $43
	db "ROWAN@@@" ; $44
	db "JUNIPER@" ; $45
	db "SYCAMOR@" ; $46
	db "KUKUI@@@" ; $47
	db "WILLOW@@" ; $48
	db "SAMUEL@@" ; $49
	db "SAMSON@@" ; $4a
	db "COZMO@@@" ; $4b
	db "FENNEL@@" ; $4c
	db "CEDRIC@@" ; $4d
	db "SILKTRE@" ; $4e
	db "BURNET@@" ; $4f
	db "MOHN@@@@" ; $50
	db "KRANE@@@" ; $51
	db "BILL@@@@" ; $52
	db "LANETTE@" ; $53
	db "BRIGETT@" ; $54
	db "CELIO@@@" ; $55
	db "BEBE@@@@" ; $56
	db "AMANITA@" ; $57
	db "CASSIUS@" ; $58
	db "MOLAYNE@" ; $59
	db "BROCK@@@" ; $5a
	db "MISTY@@@" ; $5b
	db "SURGE@@@" ; $5c
	db "ERIKA@@@" ; $5d
	db "JANINE@@" ; $5e
	db "SABRINA@" ; $5f
	db "BLAINE@@" ; $60
	db "GIOVANI@" ; $61
	db "LORELEI@" ; $62
	db "BRUNO@@@" ; $63
	db "AGATHA@@" ; $64
	db "LANCE@@@" ; $65
	db "CISSY@@@" ; $66
	db "DANNY@@@" ; $67
	db "RUDY@@@@" ; $68
	db "LUANA@@@" ; $69
	db "PRIMA@@@" ; $6a
	db "FALKNER@" ; $6b
	db "BUGSY@@@" ; $6c
	db "WHITNEY@" ; $6d
	db "MORTY@@@" ; $6e
	db "CHUCK@@@" ; $6f
	db "JASMINE@" ; $70
	db "PRYCE@@@" ; $71
	db "CLAIR@@@" ; $72
	db "WILL@@@@" ; $73
	db "KOGA@@@@" ; $74
	db "KAREN@@@" ; $75
	db "ROXANNE@" ; $76
	db "BRAWLY@@" ; $77
	db "WATTSON@" ; $78
	db "FLANERY@" ; $79
	db "NORMAN@@" ; $7a
	db "WINONA@@" ; $7b
	db "LIZA@@@@" ; $7c
	db "TATE@@@@" ; $7d
	db "WALLACE@" ; $7e
	db "JUAN@@@@" ; $7f
	db "SIDNEY@@" ; $80
	db "PHOEBE@@" ; $81
	db "GLACIA@@" ; $82
	db "DRAKE@@@" ; $83
	db "STEVEN@@" ; $84
	db "ROARK@@@" ; $85
	db "GARDEN@@" ; $86
	db "MAYLENE@" ; $87
	db "WAKE@@@@" ; $88
	db "FANTINA@" ; $89
	db "BYRON@@@" ; $8a
	db "CANDICE@" ; $8b
	db "VOLKNER@" ; $8c
	db "AARON@@@" ; $8d
	db "BERTHA@@" ; $8e
	db "FLINT@@@" ; $8f
	db "LUCIAN@@" ; $90
	db "CYNTHIA@" ; $91
	db "CILAN@@@" ; $92
	db "CHILI@@@" ; $93
	db "CRESS@@@" ; $94
	db "ROXIE@@@" ; $95
	db "LENORA@@" ; $96
	db "BURGH@@@" ; $97
	db "ELESA@@@" ; $98
	db "CLAY@@@@" ; $99
	db "SKYLA@@@" ; $9a
	db "BRYCEN@@" ; $9b
	db "DRAYDEN@" ; $9c
	db "IRIS@@@@" ; $9d
	db "MARLON@@" ; $9e
	db "SHANTAL@" ; $9f
	db "MARSHAL@" ; $a0
	db "GRIMSLY@" ; $a1
	db "CAITLIN@" ; $a2
	db "ALDER@@@" ; $a3
	db "VIOLA@@@" ; $a4
	db "GRANT@@@" ; $a5
	db "KORRINA@" ; $a6
	db "RAMOS@@@" ; $a7
	db "CLEMONT@" ; $a8
	db "VALERIE@" ; $a9
	db "OLYMPIA@" ; $aa
	db "WULFRIC@" ; $ab
	db "MALVA@@@" ; $ac
	db "SIEBOLD@" ; $ad
	db "WIKTROM@" ; $ae
	db "DRASNA@@" ; $af
	db "DIANTHA@" ; $b0
	db "ILIMA@@@" ; $b1
	db "LANA@@@@" ; $b2
	db "KIAWE@@@" ; $b3
	db "MALLOW@@" ; $b4
	db "SOPHCLS@" ; $b5
	db "ACEROLA@" ; $b6
	db "MINA@@@@" ; $b7
	db "HALA@@@@" ; $b8
	db "OLIVIA@@" ; $b9
	db "NANU@@@@" ; $ba
	db "HAPU@@@@" ; $bb
	db "KAHILI@@" ; $bc
	db "NOLAND@@" ; $bd
	db "GRETA@@@" ; $be
	db "TUCKER@@" ; $bf
	db "LUCY@@@@" ; $c0
	db "SPENSER@" ; $c1
	db "BRANDON@" ; $c2
	db "ANABEL@@" ; $c3
	db "PALMER@@" ; $c4
	db "THORTON@" ; $c5
	db "DAHLIA@@" ; $c6
	db "DARACH@@" ; $c7
	db "ARGENTA@" ; $c8
	db "PROTON@@" ; $c9
	db "PETREL@@" ; $ca
	db "ARCHER@@" ; $cb
	db "ARIANA@@" ; $cc
	db "JESSIE@@" ; $cd
	db "JAMES@@@" ; $ce
	db "CASSIDY@" ; $cf
	db "BUTCH@@@" ; $d0
	db "BONNIE@@" ; $d1
	db "CLYDE@@@" ; $d2
	db "ATTILA@@" ; $d3
	db "HUN@@@@@" ; $d4
	db "DOMINO@@" ; $d5
	db "MIROR B@" ; $d6
	db "MATT@@@@" ; $d7
	db "SHELLY@@" ; $d8
	db "ARCHIE@@" ; $d9
	db "TABITHA@" ; $da
	db "COURTNY@" ; $db
	db "MAXIE@@@" ; $dc
	db "MARS@@@@" ; $dd
	db "JUPITER@" ; $de
	db "SATURN@@" ; $df
	db "CHARON@@" ; $e0
	db "CYRUS@@@" ; $e1
	db "N@@@@@@@" ; $e2
	db "COLRESS@" ; $e3
	db "GORM@@@@" ; $e4
	db "BRONIUS@" ; $e5
	db "ROOD@@@@" ; $e6
	db "ZINZOLN@" ; $e7
	db "GIALLO@@" ; $e8
	db "RYOKU@@@" ; $e9
	db "GHETSIS@" ; $ea
	db "ANTHEA@@" ; $eb
	db "CONCORD@" ; $ec
	db "ALIANA@@" ; $ed
	db "BRYONY@@" ; $ee
	db "CELOSIA@" ; $ef
	db "MABLE@@@" ; $f0
	db "XEROSIC@" ; $f1
	db "LYSANDR@" ; $f2
	db "TUPP@@@@" ; $f3
	db "ZIPP@@@@" ; $f4
	db "RAPP@@@@" ; $f5
	db "PLUMERA@" ; $f6
	db "GUZMA@@@" ; $f7
	db "FABA@@@@" ; $f8
	db "WICKE@@@" ; $f9
	db "LUSAMIN@" ; $fa
	db "CANDELA@" ; $fb
	db "BLANCHE@" ; $fc
	db "SPARK@@@" ; $fd
	db "SATOSHI@" ; $fe
	db "TAJIRI@@" ; $ff

WonderTradeOTNames2:
	db "SHIGERU@" ; $00
	db "HIBIKI@@" ; $01
	db "KOTONE@@" ; $02
	db "KAMON@@@" ; $03
	db "YUUKI@@@" ; $04
	db "HARUKA@@" ; $05
	db "MITSURU@" ; $06
	db "KOUKI@@@" ; $07
	db "HIKARI@@" ; $08
	db "JUN@@@@@" ; $09
	db "TOUYA@@@" ; $0a
	db "TOUKO@@@" ; $0b
	db "BEL@@@@@" ; $0c
	db "KYOUHEI@" ; $0d
	db "MEI@@@@@" ; $0e
	db "HELIOS@@" ; $0f
	db "SELENE@@" ; $10
	db "MIKE@@@@" ; $11
	db "KYLE@@@@" ; $12
	db "TIM@@@@@" ; $13
	db "EMY@@@@@" ; $14
	db "CHRIS@@@" ; $15
	db "KIM@@@@@" ; $16
	db "JACQUES@" ; $17
	db "HARI@@@@" ; $18
	db "JOY@@@@@" ; $19
	db "JENNY@@@" ; $1a
	db "DELIA@@@" ; $1b
	db "DAISY@@@" ; $1c
	db "FUJI@@@@" ; $1d
	db "BAOBA@@@" ; $1e
	db "COPYCAT@" ; $1f
	db "PRIMO@@@" ; $20
	db "LOSTELE@" ; $21
	db "TEALA@@@" ; $22
	db "SELPHY@@" ; $23
	db "JOEY@@@@" ; $24
	db "CAL@@@@@" ; $25
	db "CARRIE@@" ; $26
	db "MR.PKMN@" ; $27
	db "EUSINE@@" ; $28
	db "CAMERON@" ; $29
	db "EARL@@@@" ; $2a
	db "KURT@@@@" ; $2b
	db "BEN@@@@@" ; $2c
	db "MARY@@@@" ; $2d
	db "REED@@@@" ; $2e
	db "FERN@@@@" ; $2f
	db "LILY@@@@" ; $30
	db "BUENA@@@" ; $31
	db "RANDY@@@" ; $32
	db "MAXIMO@@" ; $33
	db "FELICTY@" ; $34
	db "MONICA@@" ; $35
	db "TUSCANY@" ; $36
	db "WESLEY@@" ; $37
	db "ARTHUR@@" ; $38
	db "FRIEDA@@" ; $39
	db "SANTOS@@" ; $3a
	db "SUNNY@@@" ; $3b
	db "NAOKO@@@" ; $3c
	db "SAYO@@@@" ; $3d
	db "ZUKI@@@@" ; $3e
	db "KUNI@@@@" ; $3f
	db "MIKI@@@@" ; $40
	db "LI@@@@@@" ; $41
	db "KIYO@@@@" ; $42
	db "SCOTT@@@" ; $43
	db "BRINEY@@" ; $44
	db "STONE@@@" ; $45
	db "WANDA@@@" ; $46
	db "GABBY@@@" ; $47
	db "TY@@@@@@" ; $48
	db "RYDEL@@@" ; $49
	db "STERN@@@" ; $4a
	db "AARUNE@@" ; $4b
	db "LISIA@@@" ; $4c
	db "ZINNIA@@" ; $4d
	db "INVER@@@" ; $4e
	db "CHAZ@@@@" ; $4f
	db "KIRI@@@@" ; $50
	db "JOHANNA@" ; $51
	db "LOOKER@@" ; $52
	db "CHERYL@@" ; $53
	db "RILEY@@@" ; $54
	db "BUCK@@@@" ; $55
	db "MARLEY@@" ; $56
	db "MIRA@@@@" ; $57
	db "ROSANNE@" ; $58
	db "JULIA@@@" ; $59
	db "JORDAN@@" ; $5a
	db "DEXTER@@" ; $5b
	db "KEIRA@@@" ; $5c
	db "FUEGO@@@" ; $5d
	db "HELENA@@" ; $5e
	db "HAWES@@@" ; $5f
	db "CHARLES@" ; $60
	db "CURTIS@@" ; $61
	db "YANCY@@@" ; $62
	db "INGO@@@@" ; $63
	db "EMMET@@@" ; $64
	db "GRACE@@@" ; $65
	db "ALEXA@@@" ; $66
	db "DEXIO@@@" ; $67
	db "SINA@@@@" ; $68
	db "GURKINN@" ; $69
	db "AZ@@@@@@" ; $6a
	db "EMMA@@@@" ; $6b
	db "PHIL@@@@" ; $6c
	db "NITA@@@@" ; $6d
	db "EVELYN@@" ; $6e
	db "DANA@@@@" ; $6f
	db "MORGAN@@" ; $70
	db "RYUKI@@@" ; $71
	db "GESTER@@" ; $72
	db "IMAKUNI@" ; $73
	db "RICHIE@@" ; $74
	db "ASSUNTA@" ; $75
	db "TRACEY@@" ; $76
	db "DUPLICA@" ; $77
	db "CASEY@@@" ; $78
	db "GISELLE@" ; $79
	db "MELANIE@" ; $7a
	db "DAMIAN@@" ; $7b
	db "ALAIN@@@" ; $7c
	db "REIKO@@@" ; $7d
	db "AYA@@@@@" ; $7e
	db "RAINER@@" ; $7f
	db "SPARKY@@" ; $80
	db "PYRO@@@@" ; $81
	db "MIKEY@@@" ; $82
	db "ORVILLE@" ; $83
	db "A.J.@@@@" ; $84
	db "CAMILA@@" ; $85
	db "A@@@@@@@" ; $86
	db "SLASH@@@" ; $87
	db "ALICE@@@" ; $88
	db "LEO@@@@@" ; $89
	db "AOOOO@@@" ; $8a
	db "JIMMY@@@" ; $8b
	db "CLY@@@@@" ; $8c
	db "LI'L D@@" ; $8d
	db "ARTY@@@@" ; $8e
	db "ABE@@@@@" ; $8f
	db "BABA@@@@" ; $90
	db "EVAN@@@@" ; $91
	db "PAUL@@@@" ; $92
	db "CYAN@@@@" ; $93
	db "REVO@@@@" ; $94
	db "EVERYLE@" ; $95
	db "ZETSU@@@" ; $96
	db "KARUTA@@" ; $97
	db "NOZOMI@@" ; $98
	db "AMOS@@@@" ; $99
	db "KAITO@@@" ; $9a
	db "MEIKO@@@" ; $9b
	db "MIKU@@@@" ; $9c
	db "RIN@@@@@" ; $9d
	db "LEN@@@@@" ; $9e
	db "LUKA@@@@" ; $9f
	db "TETO@@@@" ; $a0
	db "AMI@@@@@" ; $a1
	db "MINAKO@@" ; $a2
	db "USAGI@@@" ; $a3
	db "REI@@@@@" ; $a4
	db "MAKOTO@@" ; $a5
	db "MAMORU@@" ; $a6
	db "LUNA@@@@" ; $a7
	db "ARTEMIS@" ; $a8
	db "DIANA@@@" ; $a9
	db "SAKURA@@" ; $aa
	db "TOMOYO@@" ; $ab
	db "SYAORAN@" ; $ac
	db "SHINJI@@" ; $ad
	db "ASUKA@@@" ; $ae
	db "MARI@@@@" ; $af
	db "GENDO@@@" ; $b0
	db "YUI@@@@@" ; $b1
	db "KAWORU@@" ; $b2
	db "OKABE@@@" ; $b3
	db "DARU@@@@" ; $b4
	db "KURISU@@" ; $b5
	db "SUZUHA@@" ; $b6
	db "MAYURI@@" ; $b7
	db "RUKA@@@@" ; $b8
	db "KYON@@@@" ; $b9
	db "HARUHI@@" ; $ba
	db "YUKI@@@@" ; $bb
	db "MIKURU@@" ; $bc
	db "TSURUYA@" ; $bd
	db "RYOKO@@@" ; $be
	db "ITSUKI@@" ; $bf
	db "JOJO@@@@" ; $c0
	db "JOTARO@@" ; $c1
	db "JOSUKE@@" ; $c2
	db "DIO@@@@@" ; $c3
	db "KEI@@@@@" ; $c4
	db "SAIKA@@@" ; $c5
	db "HAYATE@@" ; $c6
	db "DARUKU@@" ; $c7
	db "NAGISA@@" ; $c8
	db "BRIDGET@" ; $c9
	db "RYO@@@@@" ; $ca
	db "CLARA@@@" ; $cb
	db "HANA@@@@" ; $cc
	db "MIYUKI@@" ; $cd
	db "LUKE@@@@" ; $ce
	db "VULPES@@" ; $cf
	db "BENNY@@@" ; $d0
	db "SARAH@@@" ; $d1
	db "R.HOUSE@" ; $d2
	db "VICTOR@@" ; $d3
	db "SUNNY@@@" ; $d4
	db "CASS@@@@" ; $d5
	db "BOONE@@@" ; $d6
	db "FELICIA@" ; $d7
	db "ARCADE@@" ; $d8
	db "RINGO@@@" ; $d9
	db "PETE@@@@" ; $da
	db "TORRES@@" ; $db
	db "JACKSON@" ; $dc
	db "RANGI@@@" ; $dd
	db "REMY@@@@" ; $de
	db "SYLVIE@@" ; $df
	db "MATTHEW@" ; $e0
	db "MATEO@@@" ; $e1
	db "BABS@@@@" ; $e2
	db "PIA@@@@@" ; $e3
	db "AIZAWA@@" ; $e4
	db "SUKI@@@@" ; $e5
	db "FREDRIK@" ; $e6
	db "DRAYANO@" ; $e7
	db "HLIN@@@@" ; $e8
	db "MARCKUS@" ; $e9
	db "PUM@@@@@" ; $ea
	db "BRYAN@@@" ; $eb
	db "DON@@@@@" ; $ec
	db "MIGUEL@@" ; $ed
	db "SATORU@@" ; $ee
	db "IWATA@@@" ; $ef
	db "JUNICHI@" ; $f0
	db "MASUDA@@" ; $f1
	db "KOJI@@@@" ; $f2
	db "NISHINO@" ; $f3
	db "SOSUKE@@" ; $f4
	db "TAMADA@@" ; $f5
	db "HISASHI@" ; $f6
	db "SOGABE@@" ; $f7
	db "KEITA@@@" ; $f8
	db "KAGAYA@@" ; $f9
	db "YOSHI@@@" ; $fa
	db "MATSUDA@" ; $fb
	db "SHIGEKI@" ; $fc
	db "TETSUYA@" ; $fd
	db "OOTA@@@@" ; $fe
	db "TURNER@@" ; $ff
